name: 'Sync Repo Action'
description: 'GitHub Action to Sync Files Between Repositories.'
author: 'duygubahceci'

inputs:
  GITHUB_PAT:
    description: |
      GitHub Personal Access Token to use to get repos and write secrets
    required: true
  CONFIG_PATH:
    description: |
      The path for the sync configuration file
    required: false
  TMP_DIR:
    description: |
      The working directory where all sync operations will be done. Defaults to `tmp-${Date.now().toString()}`
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
