name: File Sync Workflow
on:
  push:
    branches:
      - "main"
jobs:
  file-sync:
    name: File Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        name: "Run My Repo Sync Action"
        with:
          GITHUB_PAT: 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
